source $HOME/.config/nvim/general.vim
source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/vim-plug/coc.vim
source $HOME/.config/nvim/vim-plug/fzf.vim
source $HOME/.config/nvim/vim-plug/signify.vim
source $HOME/.config/nvim/vim-plug/my.vim
source $HOME/.config/nvim/vim-plug/airline.vim
source $HOME/.config/nvim/vim-plug/theme.vim
source $HOME/.config/nvim/vim-plug/keys-my.vim
